### ISSUE TITLE
Belozovsky, Anna: TODOs

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/IntelliJ-Spartanizer#10]
_From @AnnaBel7 on October 28, 2016 15:12_

- [x]  Use a picture, photo or distinct avatar. Don't use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page
- [x]  State that you are (not) in search for a job

_Copied from original issue: SpartanRefactoring/Spartanizer#565_

**Comment by zvili** [comment]
_From @AnnaBel7 on October 28, 2016 15:44_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @michalcohen on October 28, 2016 15:50_

BEST partner in the world!!!

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 2:15_

Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?).

**Comment by zvili** [comment]
_From @geniashand on October 30, 2016 9:3_

Yay for Karma! ^_^

**Comment by zvili** [comment]
_From @AdiOmari on October 30, 2016 9:9_

👍

**Comment by zvili** [comment]
_From @yossigil on November 18, 2016 8:21_

:+1:

**Comment by yossigil** [comment]
How come this is assigned to Adi? @AnnaBel7

**Comment by AnnaBel7** [comment]
**Results of sprint 1:**

#16 : I imported the AST jar and started importing classes from the original Spartanizer before we decided to work on Leonidas which also uses some of the original code and the AST library.

#20 + #28 : @RoeiRaz and I worked on importing the Leonidas to intellij while using the eclipse AST library (without converting it to use PSI library). We didn't need to translate the ASTRewriter after all and managed to get Leonidas to work in intellij using jdt's AST. It compiles and works for the tippers we tested (not all of them yet).

#31 : @RoeiRaz and I continued working on Leonidas in intellij and managed to get great results, we don't have all the tippers yet but it is definitely possible to use this in our project. We uploaded our work in a separate repository to prevent it from breaking working code in this repository. A link to that repository can be found in the issue.
