### ISSUE TITLE
What should we return in getRootElementType() ?

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#100]
This method : `Class<? extends PsiElement> getRootElementType();` 
should return the element type so we can use it in `LeonidasTipper :: getPsiClass()`.
The problem is we have two types, one given in `@Leonidas(value)` of from and one given in `@Leonidas(value)` of to. 
Which one should we use?
I think the most appropriate is to return the type of `from`.
What do you think?
@amirsagiv83 @michalcohen @AnnaBel7 @RoeiRaz @RoeyMaor

**Comment by orenafek** [comment]
By the way this is our :100: Issue !!!! :fireworks: :champagne: :scream:

**Comment by michalcohen** [comment]
Well yes, The point of 'getPsiClass()' is to minimize the amount of tips for which we check 'canTip' by using the type of the element being inspected as a key to a **map** of tips. therefor, 'getPsiClass' needs to return the type on which the tip works, in our case the leonidas value of the **from** tree.

**Comment by orenafek** [comment]
Cool. just wanted to be sure.
Closing :)
