### ISSUE TITLE
issue when two tips can be applied on the same element

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/IntelliJ-Spartanizer#101]
when two tips can be applied and i try to apply the second one immediately after the first one the next exception is thrown:
![image](https://cloud.githubusercontent.com/assets/22842727/22040637/2fc83650-dd0c-11e6-8f96-8df253c1dffc.png)

I tried to debug a little (and I'll keep trying) but no conclusions yet.
@orenafek @RoeiRaz @RoeyMaor @michalcohen @amirsagiv83 did any of you encounter this problem in the past and knows how to solve it?

**Comment by michalcohen** [comment]
We encountered it when there was no findFirst() in executeAllTippers of Toolbox. But now there is (and a commented code 👎 !) maybe we need to put in th begging of any tip method, canTip() call.

**Comment by AnnaBel7** [comment]
@michalcohen since we added findFirst() you haven't got this exception?

**Comment by michalcohen** [comment]
Can you please give me a code exapmle that produces the bug?

**Comment by michalcohen** [comment]
I tried:
if (!(!(x > 0))){
    y++;
}

and got errors or exceptions 🤕

**Comment by michalcohen** [comment]
@AnnaBel7 is it still buggy?

**Comment by AnnaBel7** [comment]
it still doesn't work so well, but now it just doesn't let me open the intention actions menu

**Comment by michalcohen** [comment]
@AnnaBel7 I don't see bugs from this type anymore after the fix, can you please check if you have any more problems?

**Comment by RoeyMaor** [comment]
the exceptions are no longer present, but it seems the current solution is merely catching the exception and ignoring it. for now this might suffice, but i think this issue should remain open

**Comment by amirsagiv83** [comment]
Someone must be assigned to this issue. @michalcohen ? @AnnaBel7 ?

**Comment by michalcohen** [comment]
@RoeyMaor it wasn't just a patch, right after the annotator is done, it immediatly tries to re-annotate the psi element. since we replace the element entirely, it reaches null when executing "getContainingFile". this is why I added this ignoring catch, it happens only in this split of a second right after the annotator is done. I don't see a reason to treat it differently.

**Comment by RoeyMaor** [comment]
this makes more sense now
@michalcohen 🔝 🔝
