### ISSUE TITLE
Getting ready for the Semester Final Presentation

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#103]
Hi everyone,
We got to the grand finale of the semester' and things should be perfectly ready for Tuesday.
so, after discussing this between us, here is a list of TODO's we have to do until the presentation:

- [x] @orenafek  - Prepare the slides you were asked by Yossi.
- [x] @AnnaBel7 @RoeyMaor  - prepare the slides about the technology and architecture of our plugin.
- [x] @orenafek  - Upload the plugin to the market and create a simple install guide.
- [x] Me - prepare the PowerPoint slides for the presentation (if someone wants to join me, you're welcome.
- [x] All of us - close **ALL** issues of Sprint2 until 23.1 (Monday)

Anything I forgot?
I'm assigning only myself, and this issue (just like all others) must be closed until Monday.
@orenafek @michalcohen @RoeyMaor @AnnaBel7 @RoeiRaz 
Final push. Let's show them  what's Sparta is all about ⚔️ ⚔️ ⚔️

**Comment by AnnaBel7** [comment]
Sent slides to oren @RoeyMaor 
🐷 🎉 🎉

**Comment by RoeyMaor** [comment]
😄  @AnnaBel7

**Comment by orenafek** [comment]
All Done.
Finished Semester 1 :smile: 
Closing.
