### ISSUE TITLE
Recheck project works on different OS after last changes

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#106]
We need to figure out a way to check our code efficiently outside the Intellij inner instance.

**Comment by amirsagiv83** [comment]
I've checked the plugin on my windows computer and on my Ubuntu computer and it seems like tips are working' both regular, nanos and leonidas tippers. Anna checked the plugin on Mac and it looks like everything is fine. closing the issue.
