### ISSUE TITLE
Substituting a generic type

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#107]
When we want to create a pattern tree in which there are two generic sons (like if statement for which both "then" and "else" are generic, an exception is thrown by the copy method of CompositeElement. I've already went pretty deep on this issue last semester, and I believe I need extra pair of eyes to figure out where in all that huge messy code the exception is thrown, and what is missing in our generic type classes in order for that simple procedure to success.
This is a very critical bug since *every* new tipper we came up with last semester, will reach this bug eventually.
If someone is available before the beginning of the next semester - that will be great!

**Comment by yossigil** [comment]
sons->children (PC/Hebrenglish)
