### ISSUE TITLE
Find and replace code blocks performing "true parent finding"

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#109]
There is a new method in "step", "getHighestParent", that might shorten the software in many places. Since we saw the need in this kind of behaviour pretty late, we need to find and replace the places that perform this kind of behaviour manually.

**Comment by yossigil** [comment]
@michalcohen : take a look at class 'ancestors' and 'descendants' in the Spartanizer. They make such searches very elegant
