### ISSUE TITLE
Make sure the project runs on all computers

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#118]
Please make sure that the plugin runs with no errors on your machine (via RunIdea).
Mark yourself when done or comment if something is wrong.

- [x]  @michalcohen 
- [x] @AnnaBel7 
- [x] @orenafek 
- [x] @RoeiRaz 
- [x] @RoeyMaor 
- [x] @SharonKL 
- [x] Me

**Comment by RoeyMaor** [comment]
had to fix some things on the new computer
