### ISSUE TITLE
Major Cleanup (again)

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#128]
There was a major cleanup with the help of the code analyzer of Intellij.
![image](https://cloud.githubusercontent.com/assets/11704810/24321201/f53e8bda-1157-11e7-8bd2-517c95483113.png)

These are the only warnings left, becase most of the typos are in our names, and most of the "Declaration redundancy" is when Intellij sees the only use of a function in the tests and sujests to convert the parameters to the function to the constants used in the tests.

Whenever you push your code, please notice you don't add any other warning. Mark yourself to sign a commitment to meet the standards :) I don't want to do these cleanups any more :'(
- [x] @amirsagiv83 
- [x] @AnnaBel7 
- [x] @RoeiRaz 
- [x] @RoeyMaor 
- [x] @SharonKL 
- [x] @orenafek

**Comment by RoeyMaor** [comment]
see #131
