### ISSUE TITLE
Add yourself to contributors.txt

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#13]

**Comment by yossigil** [comment]
@michalcohen : who follows up? When would this be closed?

**Comment by orenafek** [comment]
@yossigil
As I've opened this (from @michalcohen 's computer during our meeting) I will close it as soon as RoeyR
Will be added to the repo.

**Comment by yossigil** [comment]
@orenafek : if you do not name someone to add RR then this issue will  be open forever

**Comment by orenafek** [comment]
@yossigil you're right.
@zvili would you please add Roei Rosenzwieg to this repo ?

**Comment by zvili** [comment]
Please provide Roei's GitHub username.

**Comment by amirsagiv83** [comment]
RoeiRaz

**Comment by yossigil** [comment]
:100:
