### ISSUE TITLE
Read and accept the coding standards

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/IntelliJ-Spartanizer#132]
Me and @SharonKL have posted the Coding standards for this semester here: https://github.com/TechnionYP5777/IntelliJ-Spartanizer/wiki/Coding-Standards

Each team member should mark here that he/she have read the coding standards for this semester and 
will follow them:

- [x] @amirsagiv83 

- [x] @orenafek 

- [x] @michalcohen 

- [x] @AnnaBel7 

- [x] @RoeiRaz

**Comment by amirsagiv83** [comment]
Great Job!

**Comment by amirsagiv83** [comment]
@orenafek @AnnaBel7 , please close this if you're the last one.

**Comment by orenafek** [comment]
Amazing!!!
Closing.
