### ISSUE TITLE
Importing The Leonideas To IntelliJ Using A Custom Built ASTReWriter

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#20]
Try to import the Leonidas into IntelliJ, and make it work with jdt's ASTNode.

@RoeiRaz  is on it for a few day now. Leonidas is built out of 3 classes, one of them was already moved, the second one uses the ASTrewrite and so, Roei will help me work on investigating it, hopefully using it to compile Leonidas.

**Comment by RoeiRaz** [comment]
Isn't this a duplicate of #3 ?
Anyway, regarding leonidas, we've managed to make the class **Matcher** compile in intellij. To achieve that we:

1. Added a subset of eclipse jars to the project dependencies in intellij
2. Added subsets of the classes **iz, az, Recurser, step** which are essential to make **Matcher** work.
3. Added the class Matcher to the project (without changes)

To test that it indeed functions as expected, i made a simple utility class to convert strings to ASTNode (works only on statements) and made 2 simple JUnit tests that use the basic function of **Matcher**, and they passed.

The second leonidas class, **TipperFactory**, uses ASTRewrite and Tipper classes, and we think that it would be more complicated to port it to intellij.

screenshot of the jar dependencies i used:
![dependencies](https://cloud.githubusercontent.com/assets/7161024/20651774/d8d21ef0-b4f3-11e6-93d4-af464644d750.png)

**Comment by yossigil** [comment]
:+1: :+1:

**Comment by michalcohen** [comment]
I will gladly sit with Roei to understand how does the proper environment is to be set, create a detailed explanation and make sure everybody  knows how to set it. I will create an issue as soon as I have a convenient interface. @RoeiRaz , tomorrow will you have time?

**Comment by RoeiRaz** [comment]
@michalcohen sure

**Comment by amirsagiv83** [comment]
@RoeiRaz @AnnaBel7 
Use this issue for the assignment we have decided on today.
Our mission here is to try and implement Leonidas Using the jdt's AST, trying to build our own ASTReWriter.

**Comment by RoeyMaor** [comment]
Ori roth wrote o nthe subject here:
https://github.com/SpartanRefactoring/Spartanizer/issues/876

**Comment by amirsagiv83** [comment]
Moving this issue to the next sprint, should be ready with conclusions in a week.
