### ISSUE TITLE
Collission between IntelliJ Analyzer and Spartanizer

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#24]
Some of the tippers are already suggested by IntelliJ.
If we are using the Analyzer (Alt + Enter), two solutions will be suggested.
What should we do in these cases ?

**Comment by amirsagiv83** [comment]
I think that it might be best to let the user decide. Even if it makes the same change in the code, after the change is done, our Spartanizer might have more tippers it can apply.

**Comment by RoeyMaor** [comment]
maybe to differentiate we could write each tip "x" in the analyzer as "spartanize - x", and then like amir said the user would choose

**Comment by OriRoth** [comment]
In the eclipse project we use `Tip: ` as a prefix.

**Comment by amirsagiv83** [comment]
Did you decide the way of dealing with it?

**Comment by michalcohen** [comment]
I think we should go with "Spartanize" as IntelliJ already has a mechanism of tipping in other context. I'm closing the issue.

**Comment by yossigil** [comment]
@michalcohen good point
