### ISSUE TITLE
PsiVisitor doesn't use overloading

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#25]
this is the way accept is implemented:
![image](https://cloud.githubusercontent.com/assets/11704810/20833160/d561ba18-b896-11e6-8944-cd3534f38a88.png)

And the classes to which visitElement is overloaded is only PsiElement. (the other visit methods: PsiFile, PsiBinaryFile, PsiPlainText, PsiErrorElement, PsiPlainTextFile, PsiDirectory, PsiComment are irrelevant)
I think we might want to use our own visitor with overloading to all Psi types available (or at least these we use the most).
Right now I'm dealing with the problem with the most ugly way: "if ( ... instanceof ..) else if (... instanceof ...)... "

So what do you say, should I write a new visitor or is there other way?

**Comment by michalcohen** [comment]
http://grepcode.com/file/repository.grepcode.com/java/ext/com.jetbrains/intellij-idea/12.1.2/com/intellij/psi/PsiElementVisitor.java#PsiElementVisitor.visitElement%28com.intellij.psi.PsiElement%29

The link to PsiElementVisitor

**Comment by amirsagiv83** [comment]
Are you Trying to say you don't have a way to find the most accurate type of the element you're dealing with?

**Comment by michalcohen** [comment]
No, I'm saying the visitor design pattern isn't implemented as we learned - I have no way to differ the behavior of different types elegantly, which is exactly the purpose of this design pattern

**Comment by amirsagiv83** [comment]
Have you tried searching the utils folders in the IntelliJ Psi repository?

**Comment by michalcohen** [comment]
I don't see any visitor interfaces in Util package

**Comment by michalcohen** [comment]
@RoeiRaz do you have any idea what should we do? adding "accept" method to PSI elements maybe?

**Comment by RoeiRaz** [comment]
@michalcohen The abstract class **JavaElementVisitor** solves this issue.

**Comment by RoeiRaz** [comment]
You can pass an instance of (implementation of) **JavaElementVisitor** as argument to visit. It has many abstract methods like visitAnonymousClass, visitBlockStatement, etc.
