### ISSUE TITLE
Do not commit workspace.xml

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/IntelliJ-Spartanizer#26]
leave workspace.xml out of the "staged" file group whenever you are commiting, as this messes up the project settings on individual machines

**Comment by RoeyMaor** [comment]
there might be a way to add it to the .gitignore and bypass the need to unstage each time

**Comment by RoeyMaor** [comment]
for some reason the entire .idea/ folder is in the .gitignore but workspace.xml changes are still commited

**Comment by RoeyMaor** [comment]
**staged and unstaged**
here is an example on how to move workspace.xml to the unstaged group:

![image](https://cloud.githubusercontent.com/assets/16507852/21018810/f537d248-bd76-11e6-961c-c283f2a76edb.png)

so in general:
to move a file from staged to unstaged: use git reset
to move a file from unstaged to staged: use git add

unstaged files will not be committed.

**Comment by RoeyMaor** [comment]
@amirsagiv83

**Comment by amirsagiv83** [comment]
Thanks, Really helpful.
In case someone need it in the future, make sure to use commit -m and **not** -am.
@RoeiRaz @orenafek @AnnaBel7 @michalcohen 
Closing the issue.

**Comment by RoeyMaor** [comment]
*mad face*

**Comment by amirsagiv83** [comment]
I don't think this should keep being open so,
@RoeyMaor  @RoeiRaz  @michalcohen  @orenafek @AnnaBel7 
Please make sure to remember that,
orelse, @RoeyMaor is gonna be mad. 😨
