### ISSUE TITLE
Implementing Leonidas on IntelliJ using Psi - Continue

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#27]
this is the next part for the #23 issue. please keep updating here!

**Comment by RoeyMaor** [comment]
conclusion so far: this is definitely possible, given enough time.
Made progress:
-UserDefinedTipper translated completely.
-Matcher and TipperFactory partially translated
-added many helpful classes required for translation
-enhanced the auxiliary package
Although possible, as stated above, this takes time, as each component that is translated reveals another one it depends on that also needs to be translated. Currently, **the only real obstacle left is how to use the wizard util class with psi.**
