### ISSUE TITLE
Importing Leonidas from Eclipse to Intellij without translating it to Psi

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#28]
this is the next part for the #20  issue. please keep updating here!

**Comment by RoeiRaz** [comment]
After importing the JAR file of the original spartanizer plugin (and making some more small tweaks), we've managed to use leonidas functionalities without changing ASTRewrite.
We wrote a small function that given a Tipper and a String, can compute the tipper outcome on that string and return it. It works with tippers generated by leonidas (we didn't check it yet on regular tippers).

It may be possible to use this function to implement our plugin - we can create an annotator that for each PsiElement **p** will transform **p** to an ASTNode **a**, then will check which tippers are capable of tipping it, and finally will use the function we wrote to get a string which will be plugged into the code instead **p**.

@amirsagiv83 what do you think?

**Comment by amirsagiv83** [comment]
It's great that you managed to tip a string. About the second part, this is a possibility we discussed about a few weeks ago, Do you think doing it this way is better than implementing our own ASTRewriter?

**Comment by RoeiRaz** [comment]
I'm changing the title - it wasn't necessary to make any changes to ASTRewrite.

**Comment by RoeiRaz** [comment]
Done. for results take a look at #31
