### ISSUE TITLE
Implement Leonidas in IntelliJ

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#3]

**Comment by yossigil** [comment]
Who is assigned? What's the milestone? Do we need to create one? Labels?

**Comment by yossigil** [comment]
Who is assigned? What's the milestone? Do we need to create one? Labels? @michalcohen

**Comment by michalcohen** [comment]
I think it is too big for an issue... It is practically the core of the project
finer graining is needed, what do you think?

**Comment by yossigil** [comment]
@ROEYRAZ and @amirsagiv83 : please repprt here.
@michalcohen : problem solved changed to "prototype".

We have to get the issues going!

**Comment by amirsagiv83** [comment]
After deciding to try and implement Leonidas in two different ways, I'm closing this issue and opening a new one more specific.
