### ISSUE TITLE
Presenting the results of sprint 1

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#30]
- [x] Each team member makes a list in his TODOs page of all issues he contributed to.
- [x] Make sure that installation is clear and smooth enough so it can be done by passers by
- [x] Coordinate a meeting, feel free to use Telegram and add me
- [x] Make sure the code runs on eclipse, it is spartanized, etc.
- [x] Let people know that we up to reflection so they should think on what went well and not so well.
- [x] Feel free to edit and create further issues if necessary.
- [x] Feel free to sort items as necessary
- [x] Make a "github release"

**Comment by amirsagiv83** [comment]
Let's arrange the sections so we don't miss something.

**Sections 1:**
Please make sure each one of you complete this task and when you're done, check your box (So i'll know when to check the box in the above issue):
- [ ] @michalcohen .
- [ ] @orenafek .
- [ ] @AnnaBel7 .
- [ ] @RoeyMaor .
- [ ] @RoeiRaz .
- [ ] Me.

**Sections 2,4,8:**
This is Michal's and Oren's responsibility, make sure to check the boxes in the issue when you're done. 

**Section 3:**
@yossigil . Would you like us to add you back to the Telegram group?
Our meeting is as usually on Monday 16:30.

**Section 5:**
Each couple should conclude their results and opinions so it it will be easier to make decisions about our future work and architecture.

**Sections 6,7:**
Feel free to add and edit as you wish, I'll check the boxes before our next meeting.

Good Luck everybody 😄

**Comment by yossigil** [comment]
Can you please add me back to your telegram group?

**Comment by orenafek** [comment]
what is a "github release" ?

**Comment by amirsagiv83** [comment]
Completed all Tasks. Closing the issue.

**Comment by yossigil** [comment]
Good job team!
@amirsagiv83 @orenafek @AnnaBel7 @michalcohen @RoeiRaz @RoeyMaor
