### ISSUE TITLE
Progress report - Using existing tippers in intellij

### ISSUE THREAD

**Issue by RoeiRaz** [TechnionYP5777/IntelliJ-Spartanizer#31]
Our original task was #28. We expanded our goals a bit, and managed to use tippers from the original spartanizer plugin by:
- Parsing the file in intellij with an ASTParser, and linking each PsiElement with its corresponding ASTNode in the document.
- Defining an externalAnnotator in our plugin that iterates the PsiElements and tries their matching ASTNode on tippers from some collection. (Clarification: we didn't implement any tipper, those are the tippers from the original spartanizer!)
- The actual text replacement is done by calling the method VitualFile.setBinaryContent

Here are some demos:
![treasure](https://cloud.githubusercontent.com/assets/7161024/21059509/66a78dd6-be4b-11e6-81a3-4c7fd48dc74f.png)

![demo1](https://cloud.githubusercontent.com/assets/7161024/21059511/692a6740-be4b-11e6-9376-498d7c2f84b8.png)

![demo2](https://cloud.githubusercontent.com/assets/7161024/21059515/6d095ac4-be4b-11e6-9cc4-1af6a0051f03.png)

**Comment by RoeyMaor** [comment]
This is amazing, and might save a lot of work 💯 :-)

**Comment by AnnaBel7** [comment]
In order not to break the current repo we uploaded our work to a separate one.

@RoeyMaor @michalcohen @orenafek @amirsagiv83 
check it out: [https://github.com/AnnaBel7/IntellijDemo](url)

**Comment by amirsagiv83** [comment]
Link isn't working 😢 😭

**Comment by amirsagiv83** [comment]
Great and really impressive job!
Make sure to prepare a short presentation of your work for Monday's meeting! 😄

**Comment by orenafek** [comment]
Awesome job guys!

**Comment by amirsagiv83** [comment]
I think You did a great job and completed the task you were on. Closing the Issue, Well Done :+1: :smile:
