### ISSUE TITLE
Adopting new approach & rearranging the repository.

### ISSUE THREAD

**Issue by RoeiRaz** [TechnionYP5777/IntelliJ-Spartanizer#33]
After a discussion we have decided to use the existing libraries from [the original spartanizer project](https://github.com/SpartanRefactoring/Spartanizer) (#31).
The contents of the repository will be replaced with the relevant source and build files shortly after the publication of this issue.
Check yourselves after you've managed to clone-build-run the plugin:
- [x] @amirsagiv83 
- [x] @michalcohen 
- [x] @RoeyMaor 
- [ ] @orenafek 
- [x] @AnnaBel7 
- [x] @RoeiRaz

**Comment by AnnaBel7** [comment]
A guide explaining the source files will be added tomorrow.

**Comment by amirsagiv83** [comment]
At least in on my computer, when I'm running the plugin and I press the tip, everything works. If I press the tip again (even if I wait 10 sec), nothing happens. Only when I press it for the second time, the tip works again.

Do we know the reason for that? anyone else has this problem?
@RoeiRaz @AnnaBel7

**Comment by AnnaBel7** [comment]
Yes, it happens because the parsing of the source is slow

**Comment by RoeiRaz** [comment]
@amirsagiv83 Maybe disabling the annotation after the user actives the intention would fix this problem. wanna create a new issue about it?  😄

**Comment by amirsagiv83** [comment]
Sure 👍 I'll just need a little time to study your work to get it done.

**Comment by amirsagiv83** [comment]
closing the Issue. changed the approach again..
