### ISSUE TITLE
Writing tests for 'PsiAstMatching' class.

### ISSUE THREAD

**Issue by RoeiRaz** [TechnionYP5777/IntelliJ-Spartanizer#35]
Feel free to assign yourself if you want to help. Currently (d1ec6f5ca30858024db97c9cb43c7ea7f72b8ce0) the class **PsiAstMatchingTest** contains an example for creating a PsiFile from string for testing purposes.

**Comment by RoeyMaor** [comment]
added myself, i will need a brief from you before i can start helping though 👍

**Comment by amirsagiv83** [comment]
Not relevant anymore. Closing
