### ISSUE TITLE
undoing a spartanizer change with ctrl-z

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/IntelliJ-Spartanizer#37]
does anyone know of cases where ctrl-z fails to work for undoing a change made by a tipper?

**Comment by amirsagiv83** [comment]
Are you asking about our plugin? the Eclipse plugin?

**Comment by RoeyMaor** [comment]
ours

**Comment by amirsagiv83** [comment]
Why do you ask? We only have one tip working

**Comment by RoeyMaor** [comment]
? we have all of the tippers of the eclipse project to our disposal!
anyways, i will reopen this issue later, when it is more relevant
