### ISSUE TITLE
Install gradle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#40]
And explain why it is essential.

**Comment by RoeiRaz** [comment]
Done.
The reason we prefer gradle is for its [convenient plugin development tool for intellij.](https://github.com/JetBrains/gradle-intellij-plugin)

**Comment by yossigil** [comment]
Huh? How is this relevant? "
The reason we prefer gradle is for its convenient plugin development tool for intellij."

**Comment by RoeiRaz** [comment]
There is a plugin for gradle (https://github.com/JetBrains/gradle-intellij-plugin) that adds helpful gradle tasks (like `buildPlugin` and `runIdea` that open up a new instance of IntelliJ loaded with our plugin). It also automatically adds intellij specific dependencies. we haven't found something similar for maven.
Why isn't it relevant?

**Comment by yossigil** [comment]
This paragraph hit the nail on the head! good job

**Comment by RoeiRaz** [comment]
👍
