### ISSUE TITLE
Create README.MD

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#41]
Include contributor names, and ref to spartanizer

**Comment by amirsagiv83** [comment]
@michalcohen , I assigned you because you know what's going on with the readme file.
If you think there is nothing to edit in it, or, When you're done changing it,
Close the Issue. 😄

**Comment by AnnaBel7** [comment]
The old readme file was restored so maybe just some editing is needed

**Comment by michalcohen** [comment]
Updated.
