### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#42]
Check with @KaplanAlexander re: Jenkins

**Comment by michalcohen** [comment]
Is there anything left doing here? @RoeiRaz

**Comment by RoeiRaz** [comment]
yes @michalcohen

**Comment by RoeyMaor** [comment]
![image](https://cloud.githubusercontent.com/assets/16507852/22076985/08b13904-ddbb-11e6-923a-db691e4f6ada.png)

the CI thumbnail in the readme isn't loading

**Comment by RoeyMaor** [comment]
@RoeiRaz has solved it 👍
