### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#43]
How should the packages be named?

**Comment by amirsagiv83** [comment]
I think the naming should be decided only after thinking about the structure and architecture on the next meeting, Don't you think?

**Comment by yossigil** [comment]
I mean il.ac.technion or some other package root name.

**Comment by amirsagiv83** [comment]
Can you explain what's the purpose of this root name? is it a convention of the course?

**Comment by yossigil** [comment]
Why do people use Xmas trees (wear cloths)? It is tradition, not much more... following what everyone else does.

**Comment by amirsagiv83** [comment]
So I think the best way is to go over one or two projects in the course and adopt the naming of the packages, just for consistency.

**Comment by yossigil** [comment]
How about `il.org.spartan.ispartanizer`?
