### ISSUE TITLE
Tree matching libraries

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#45]
Check if there are any in Java.

**Comment by amirsagiv83** [comment]
I haven't checked it out in any way yet, but I found this repo of byteseek library.
maybe it can help somehow?

[byteseek](https://github.com/nishihatapalmer/byteseek)

from a short search I didn't find any big and professional tree matching libraries,
I'll continue my search.

**Comment by yossigil** [comment]
:+1: seems like deadend

**Comment by amirsagiv83** [comment]
:cry:
