### ISSUE TITLE
Compile a list of nanos

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#46]

**Comment by amirsagiv83** [comment]
Opened each member of the group a co responding Issue. Closing this one.

**Comment by yossigil** [comment]
@orimarco : can you please point them to some more or less stable list of nanos so they can shortlist it?

**Comment by amirsagiv83** [comment]
I talked with Ori yesterday and asked him for a list, for starters he gave us the 6 patterns I opened issues for.
