### ISSUE TITLE
Create New Nano Pattern - LispLastElement

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#48]
Create a new nano pattern tipper based on the the LispLastElement nano pattern from the Eclipse Spartanaizer Plugin.

**Comment by michalcohen** [comment]
OMG your tip is soooooo cool! Isn't it supposed to be though, ListLastElement?

**Comment by AnnaBel7** [comment]
@michalcohen it was LispLastElement in the original spartanizer, but you're right, it seems to be working just for lists as not all collections have `get` method

**Comment by michalcohen** [comment]
Got it, So maybe the name of the class needs to remain the same for later compatibility, but the description to the user should be "replace " + psiMethodCallExpression.getText() + " with list last"

**Comment by AnnaBel7** [comment]
@michalcohen It's a good idea, I changed it.

seems to be finished , closing the issue.
