### ISSUE TITLE
Create New Nano Pattern - AnyMatches

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#49]
Create a new nano pattern tipper based on the the AnyMatches nano pattern from the Eclipse Spartanaizer Plugin.

**Comment by RoeyMaor** [comment]
a bug with psi itself causes PsiForeachStatement to never be recognized in the annotator, or as part of the file, even when existant in code.
printing all of the PsiElements in the file (in the spawned IDE) reveals that PsiForeachStatement isnt even there, nor an element that contains the code of the for loop only.
normal for (not foreach) works fine.
also, in the development ide (not the spawned one), if you write a for each loop then indeed a PsiForeachStatement is visible in the psi viewer.

so it looks like i cannot do any tipper that searches for a foreach statement with the conventional tools.

**Comment by amirsagiv83** [comment]
@RoeyMaor make sure to close this as soon as you can.
