### ISSUE TITLE
Create New Nano Pattern - DefaultsTo

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#50]
Create a new nano pattern tipper based on the the DefaultsTo nano pattern from the Eclipse Spartanaizer Plugin.

**Comment by orenafek** [comment]
Done.
Waiting for #57 to complete.
Closing until its resolved

**Comment by amirsagiv83** [comment]
@orenafek   make sure to close this as soon as you can.

**Comment by orenafek** [comment]
Done :)
Closing
