### ISSUE TITLE
Create New Nano Pattern - SafeReference

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#51]
Create a new nano pattern tipper based on the the SafeReference nano pattern from the Eclipse Spartanaizer Plugin.

**Comment by amirsagiv83** [comment]
I need a little help,
My tip is supposed to change a legal java code to use ?. operator which doesn't exist in Java.
Problem is, you can't create a PsiElement that doesn't represent a legal java code.
moreover, I don't see the point of changing the code to use ?. if we don't make Java's compiler recognize it.
What am I supposed to do?
@orimarco @yossigil

**Comment by yossigil** [comment]
Clever Java library? @orimarco

**Comment by amirsagiv83** [comment]
After thinking about solutions I have some conclusions.
We can't just replace the conditionalExpression with a method and paste it somewhere in the file because it will fail if we have inner classes or something similar.
There is a possibility to create a Util class in the customer's project and paste the nano methods inside, but it's not that simple. We wouldn't want the customer to see the content of this class or even the class itself, so maybe a library is needed to be created and installed with the plugin?
In my opinion this is a decision to be made in the next meeting.
So, until decisions will be made, I will leave the nano pattern to replace the legal Java code with a String containing "x?.y", just until it will be ready and done.
Also, I'll exclude it from the Working tippers pool.
@orenafek @michalcohen @AnnaBel7 @RoeiRaz @RoeyMaor 
Please make sure you read this cause we have to talk about it on Monday. If you have any idea for a clever solution, please comment.

**Comment by yossigil** [comment]
Fols. Talk to @orimarco: he has investigated and done that.

**Comment by amirsagiv83** [comment]
I talked to @orimarco  and Ori Roth, I think I understand the problems and our options. Tomorrow we will discuss this and make decisions and guidelines.

**Comment by amirsagiv83** [comment]
Note:
I've decided to make the tip work only with x.y where y is a field or a method with no params.
The reason for this decision is that I'm using lambda expressions and accepting params will force the user to make them finals.

Fixed the canTip method and made the nano work in the unified way!

Done.
Closing the Issue!
