### ISSUE TITLE
Work on our nano-patterns in a unified way

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/IntelliJ-Spartanizer#55]
We should work in a unified way,  we have multiple choises:

1) implement the nano patterns such that the functions created are written in the same file where the  pattern was replaced by the function call.
cons of this way:
- the code will be really bloated, a lot of code duplication

2)  implement the nano patterns such that the functions created are all written in the same project-global file (the identity of this file should be agreed by all team members) used only for nano-pattern created functions. this method was recommended by ori roth.

3) implement the nano patterns such that the functions created are written into a library. this method was noted as very hard by ori roth, and suggested we should not take this path.

as we are all supposed to implement a nano-pattern this week, it is critical we choose 1,2 or 3 ASAP and work accordingly.

**Comment by amirsagiv83** [comment]
As I said already in #51 , We should discuss this tomorrow on our meeting

**Comment by amirsagiv83** [comment]
We've made a decision. an Issue will be opened about it.
