### ISSUE TITLE
iz.java issue

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/IntelliJ-Spartanizer#56]
in method `methodCallExpression` checks if the `PsiElement` is of PsiMethodCallExpression class, but it is an interface and therefore the method always returns false.

Check if the problem exists in more methods

**Comment by amirsagiv83** [comment]
Who is assigned to this?

**Comment by RoeyMaor** [comment]
changed the typecheck macro to work with isAssignableFrom, which considers both superclasses and "superinterfaces"
if you think this is ok now close this issue

**Comment by AnnaBel7** [comment]
seems ok now, closing the issue
