### ISSUE TITLE
Implement the unified way to work with nano pattern's methods

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#57]
In the meeting today (26.12.16) we decided that our plugin will create a directory in the client's code in which we will create a util class containing all the methods that are used by the nano patterns tips.
This way, there will be no dependency on any jar file in the client's code.

@michalcohen and @AnnaBel7 , This is your mission. Please report your progress here and when you're done, write a small instructions comment and each member will move his first nano to to work in your way.

Good luck! 😄

**Comment by AnnaBel7** [comment]
### how to make your tipper work the unified way

**1.** first of all you need to make sure your tipper extends `NanoPatternTipper`.
**2.** you will need to add your method to `resources/spartanizer/SpartanizerUtils.java`.
**3.** you should not override `tip` anymore, so don't forget to delete it.
**4.** override the `createReplacement` method, which gets the original element and returns a new element that will replace the original one in the psi tree.
**5.** if your tipper wasn't extending `NanoPatternTipper` before, you will have to override the `pattern` method as well. at least for now this method returns `tip(¢)` where `¢` is the parameter of the method.

@RoeyMaor what is the purpose of the `pattern` method?

mark yourself when you finished converting you tipper to the unified way and I will close the issue:

- [ ] @amirsagiv83 
- [ ] @orenafek 
- [ ] @michalcohen 
- [ ] @RoeiRaz 
- [ ] @RoeyMaor 
- [ ] me

**Comment by michalcohen** [comment]
@orenafek @RoeiRaz @RoeyMaor  don't forget to assign yourself once you are done converting your code

**Comment by orenafek** [comment]
Done :)
Sorry for the delay, Iv'e been having some real GIT issues after the whole repackaging **twice** of the project.

**Comment by yossigil** [comment]
💯

**Comment by RoeyMaor** [comment]
wow i only saw this now, will update

**Comment by RoeyMaor** [comment]
due to what i wrote on #49, this is irrelevant to me as of now

**Comment by michalcohen** [comment]
@RoeiRaz when you can mark yourself - fill free to close the issue :)

**Comment by amirsagiv83** [comment]
@RoeiRaz  I saw you closed the delegator nano issue, can we close this?

**Comment by RoeiRaz** [comment]
👍
