### ISSUE TITLE
Defining Leonidas Language

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#59]
Our job is to define the details of the language for future use.

@orenafek @RoeiRaz @michalcohen @RoeyMaor @AnnaBel7 
All members should follow this Issue to make sure you agree with the decisions made here.
If you don't, please comment and we will discuss on it.

**Comment by orenafek** [comment]
We've begun defining the lang, but we believe that it won't be complete until we start using it and see what's redundant and what's missing.

**Leonidas Language V.01**
1. Tokens

     Basic Tokens:
   - `$L` - Literal
   - `$S` - Statement
   - `$T` - Type
   - `$V` - Variable
   - `$X` - Expression

     Literals:
   - `$L` - Literal
   - `$S_L` - String Literal
   - `$N_L` - Numeric Literal (anything inherits from `Number` [Integer, float, ....])
   - `$C_L` - Character Literal
   - `$B_L` - Boolean Literal (either `true` or `false`)

     Types:
   - `$T` - Type
   - `$P_T` - Primitive Type (`int`, `float`, `byte`, `char`, `double`, `boolean`, `short` and `long`)
   - `$W_T` - Primitive Wrapper Type (`Integer`, `Float`, `Byte`, `Character`, `Double`, `Boolean`,
       `Short` and `Long`)
   - `$C_T` - Class Reference Type (e.g. `Object`, `String`, `Car`)
   - `$I_T` -  Interface Reference Type (e.g. `Comparable`, `Enumerable`) 
   - `$E_T` - Enum Reference Type 

     Expressions:
   - `$X` - Expression
   - `$B_X` - Binary Expression (e.g. `a < b`)
   - `$L_X` - Lambda Express
   - `$I_T` -  Interface Reference Type (e.g. `Comparable`, `Enumerable`) 
   - `$E_T` - Enum Reference Type 

1. Rules
    _Leonidas Rule_ is a rule in the form `<LHS> => <RHS>` where every time a legal java snippet represented by the <LHS> appears in the code, it can be replaced by the `<RHS>` if it is a legal java snippet. 
`<LHS>` and `<RHS>` can be one of the following :
- Legal, compile-able Java 8 Code
- Leonidas Token (any Expression Starting with `$Ψ` where Ψ ∈ {L,S,T,V,X})
- Combination of the two above

**Comment by orenafek** [comment]
@amirsagiv83 @RoeiRaz @RoeyMaor @AnnaBel7 @michalcohen 
your comments please :)

**Comment by amirsagiv83** [comment]
Looks Great!

**Comment by amirsagiv83** [comment]
After the meeting yesterday we are trying a different approach to implement Leonidas, so,
Closing the issue.

**Comment by RoeyMaor** [comment]
![image](https://cloud.githubusercontent.com/assets/16507852/21654304/aae5b366-d2bd-11e6-95b2-2d8cbf14c16f.png)

that's the recently changed leonidas dictionary (eclipse), as a comparison

@amirsagiv83 please update me on that new way

**Comment by amirsagiv83** [comment]
@RoeyMaor  Still relevant?

**Comment by amirsagiv83** [comment]
Don't see how this is relevant anymore so I'm closing this.
