### ISSUE TITLE
Merging with intellij

### ISSUE THREAD

**Issue by RoeyMaor** [TechnionYP5777/IntelliJ-Spartanizer#60]
**Merging tutorial**
Following some conversations we had, it seems  like some of us (including me), are still GIT-o-phobic.
Even in the darkest of times (where we are forced to choose between keeping our changes, or override changes of others), there is always light at the end of the tunnel :1st_place_medal: 
many times fine-grained merging is needed (and not simply overriding or accepting entire files).

we pray to the git god to never see this message:
 
![image](https://cloud.githubusercontent.com/assets/16507852/21486884/4b6b0afc-cbc5-11e6-9844-f3b941581648.png)

:-(
Its ok, Follow:
* commit your changes locally.
* pull again from within intellij, in order to teach it about our conflicts: 
![image](https://cloud.githubusercontent.com/assets/16507852/21486885/54af546a-cbc5-11e6-828b-a3374e69e1e5.png)

* now you will see a list of pulled items, divided into files that were simply taken from the server, and files that have conflicts between our commit and the server (we need to take care of each of these)
*for each file in the merged with conflicts group, select it, and then click VCS->Git->Resolve conflicts:
![image](https://cloud.githubusercontent.com/assets/16507852/21486887/61283914-cbc5-11e6-8eb6-4c89bb69f737.png)
![image](https://cloud.githubusercontent.com/assets/16507852/21486888/6543eff2-cbc5-11e6-9d15-e8bd32113c09.png)
 
* Click merge in the dialog box, you will be prompted to the conflict resolution tool:
![image](https://cloud.githubusercontent.com/assets/16507852/21486894/6db9dc82-cbc5-11e6-9bfb-7d42bfd754a7.png)
 
In that tool you will see on the left your version of the file, and on the right the server’s version.
for each individual conflict within the files Clicking on a >> or << will decide which side will be included in the result file for that specific conflict (in some cases both sides can be included).
Conflicts are devided into two, green conflicts are ones that do not contradict each other, and could be solved by simply adding both the changes from us and from the server (usually what is done to solve them). The middle result coloumn after accepting both changes:
  
![image](https://cloud.githubusercontent.com/assets/16507852/21486896/75bea0d4-cbc5-11e6-9397-8cbc191c32ff.png)

On the other hand, red conflicts contradict each other, and to solve them you must first choose a side (>> or <<), and then manually change the code in the middle coloumn (result), to compensate the choice of a specific side.
*Hit apply, and then commit again, with a message that says “merged conflicts”.
*now you will be able to push and pull :)
![image](https://cloud.githubusercontent.com/assets/16507852/21486897/7b1d90bc-cbc5-11e6-82ba-3d7d07ace09a.png)

**Comment by amirsagiv83** [comment]
Great! super useful.
Can you copy this to a wiki page in the project repo?

**Comment by orenafek** [comment]
Moved it to wiki.
Closing
