### ISSUE TITLE
Enhance the new TipperTest class

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#61]
I've opened `TipperTest `, an intermidiate layer for capturing common & default behavior when testing
new tippers.
This class extends `PsiTestCase` so we can use it with the raw PSI elements (such as `PSIClass`, `PSIFile` etc.)
**IMPORTANT !!!**
Always make sure that your test methods start with the `test` prefix, because `PsiTestCase` is JUnit 3 compatible. 

@amirsagiv83 @michalcohen @AnnaBel7 @RoeiRaz @RoeyMaor

**Comment by orenafek** [comment]
It is sufficient for now, but upon proceeding with the tippers writing and testing, more common behavior should be extracted on demand.
So for now labeling this as On Hold.

**Comment by RoeyMaor** [comment]
This class helps a lot with testing, kudos @orenafek

**Comment by amirsagiv83** [comment]
Think we all use this class already and we all upgrade it as we go, so closing the issue.
Great job @orenafek
