### ISSUE TITLE
Optimistic Tipper

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#65]
After discussing the problems with the SafeReference tipper, regarding the methods sending through lambda expressions, we decided to try and update the canTip for patterns of this kind.

We need to try and compile the change in the canTip part of the process so we can see whether or not the change is legal. Pay attention to the problem we have with finals and effectively finals.
Yossi suggested an idea in which we will test the errors in the code before the change and after it and compare them.
Find the best way of doing that. 
Good Luck!!

**Comment by RoeyMaor** [comment]
@RoeiRaz , is e2e2e24 related to this?

**Comment by RoeyMaor** [comment]
@amirsagiv83 , @RoeiRaz: could any of you please write the problematic example that involved finals from the meeting here?

**Comment by RoeyMaor** [comment]
We can now detect syntax errors on the fly:
![image](https://cloud.githubusercontent.com/assets/16507852/21661020/be3257d6-d2da-11e6-9493-5b5da59f5e7b.png)

**Comment by RoeyMaor** [comment]
I finally found a way to detect compilation errors at run time. 
now we can detect not only syntax errors, but any semantic error that is discovered at compile time,
such as changing final variables:
![image](https://cloud.githubusercontent.com/assets/16507852/21732689/58304eae-d463-11e6-8c9a-f5be02ff33a6.png)

![image](https://cloud.githubusercontent.com/assets/16507852/21732702/75f5245a-d463-11e6-809f-6790574e4376.png)

**Comment by RoeyMaor** [comment]
if anyone wants to check compilation errors at run time for a PsiFile (after you try your tipper in code) you are welcome to use haz.compilationErrors
since run-time compilation is resourceful if done many times, it first checks for syntax errors, which could be detected quickly by searching PsiError elements:

![image](https://cloud.githubusercontent.com/assets/16507852/21733029/1878a87c-d465-11e6-955b-75ac0ab9fce3.png)

**Comment by michalcohen** [comment]
Cool! 👍

**Comment by RoeyMaor** [comment]
should we try and integrate this or go with the specific direct way that only counters final variable issues?
once this question is answered by the team leader @amirsagiv83 i will close this

**Comment by amirsagiv83** [comment]
If I remember correctly, Yossi wants us to implement this fully so we can use it not only on final variables.
I think you should try and investigate it more, and if it's a dead end, we will think about what to do.
And I'm not the team leader..

**Comment by RoeyMaor** [comment]
im closing this because of what we discussed about in the meeting
