### ISSUE TITLE
Implement Leonidas Using Meta Info - Annotations

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#66]
You need to implement as many tips as you can using the method discussed in the meeting (Annotations,Before methods, etc...).
Feel free to upgrade the implementation if you have any interesting conclusions.
Make sure to cooperate with @michalcohen  and @AnnaBel7 beacuse your missions are very related.

Good Luck!

**Comment by amirsagiv83** [comment]
@orenafek , if you're done, or when you're done,
Make sure to sum up your work in a couple of words so everyone can read and understand the results, and close the issue.

**Comment by AnnaBel7** [comment]
@amirsagiv83 the summation will be in a wiki page together with issue #58 as written in #80.

@orenafek do you think you can close this issue?

**Comment by amirsagiv83** [comment]
@orenafek  can we close this?

**Comment by orenafek** [comment]
The basic exists, but Leonidas will surly be changed and enhanced later on. closing for now. 
If a major redesigning is needed, this will be reopened.
