### ISSUE TITLE
Move unless tests

### ISSUE THREAD

**Issue by amirsagiv83** [TechnionYP5777/IntelliJ-Spartanizer#72]
@michalcohen , please move the tests you wrote for unless nano to the package below the one it is in right now (tippers instead of plugin.tippers), and change it to work with TipperTest class (update it if you need/want).

**Comment by michalcohen** [comment]
I see no plugin directory at all :o 
The test directory is in src and the resources for these test is outside src? Does anyone knows why is it like that? @amirsagiv83 @AnnaBel7 @RoeiRaz @RoeyMaor @orenafek

**Comment by RoeyMaor** [comment]
@michalcohen 
that's because i moved it like amir said before seeing this issue
i think this can be closed now

**Comment by RoeyMaor** [comment]
@michalcohen only testResources exists
