### ISSUE TITLE
Make sure everyone understand how to add custom data to PsiElements

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#73]
To our mistake, there is a way to add our own data to every PSIElement .
All we have to do is to use these methods:
`putUserData(Key<T>,T)` and `getUserData(Key<T>)`
It is important everyone reads this, so mark yourself upon reading.

- [x] @amirsagiv83 

- [x] @michalcohen 

- [x] @AnnaBel7 

- [x] @RoeyMaor 

- [x] @RoeiRaz 

@yossigil , FYI, sorry for misleading you on Monday.

**Comment by RoeyMaor** [comment]
this could help the ones working on the tree matching algorithm, as probably a good algorithm requires saving custom data on the nodes while traversing

**Comment by amirsagiv83** [comment]
Great, looks like it makes our work a little more comfortable. Everybode know, Closing the issue
