### ISSUE TITLE
Openning IDEA after the SpartanizerUtils already present in the user's Project, causes an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#74]

**Comment by orenafek** [comment]
@amirsagiv83 
assign this to the most relevant team member

**Comment by michalcohen** [comment]
Can't replicate this bug...
@amirsagiv83 if the bug still exists after pulling, can you please send me a screenshot of IntelliJ instance that produce the bug and the bug report?

**Comment by amirsagiv83** [comment]
I didn't actually see the bug, @orenafek  is the one who encountered it so, 
Oren, can you see if the bug still exists?

**Comment by orenafek** [comment]
This is really weird, but I don't have this bug anymore.
I guess it resolved itself ..... :|
closing for now.
