### ISSUE TITLE
Write wiki on leonidas operation

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/IntelliJ-Spartanizer#80]
Write explanation on leonidas operation so that everybody can expend its functionality.

**Comment by amirsagiv83** [comment]
Try to make this wiki ASAP so we can start working on new tips.

**Comment by amirsagiv83** [comment]
Is someone working on this? I think it can be really helpful if we can read a little about the it before the meeting.

**Comment by AnnaBel7** [comment]
I thought the meeting is instead of the page, I'll start working on it.

**Comment by AnnaBel7** [comment]
@orenafek I think it's better if you write about your part as you understand it the best

**Comment by AnnaBel7** [comment]
I added a page with the general way of work of the matcher and the replacer.

@orenafek please add information about the annotations and the way the generic trees are built
@michalcohen you are more than welcome to go over what I wrote and fix/change/add whatever you think

**Comment by orenafek** [comment]
Done. Closing

**Comment by orenafek** [comment]
Finished this one, @amirsagiv83 FYI
