### ISSUE TITLE
Major cleanup and conventions- please read before PULL!

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#81]
A major code cleanup has been performed!
the following classes were deleted since they have no use right now:
- iz_old*
- Matcher
- PsiStringConverter
- AnyMatch
- TipperFactory
- UserDefinedTipper

* iz_old was mostly merged with iz

I know a **lot** of effort was given in these classes and that is why I warn you - so you can copy them to your local machine and if in the future there will be found a use, no double work will be done.

- Modular
- Nominal
- Structural
- TipperCategory

are they needed? if not please delete them.

Conventions!
- Date Day(two digits)-Month(two digits)-Year(four digits)
- please always add @author and @since to your new classes
- JavaDoc comments: don't write an enter underneath them

TODOs were added - go through them, if anything is relevant and can be done, please do :)

check yourself once your read this issue

- [x]  @orenafek 
- [x] @amirsagiv83 
- [x] @AnnaBel7 
- [x] @RoeiRaz 
- [x] @RoeyMaor

**Comment by amirsagiv83** [comment]
@RoeyMaor  close this when you read it.
