### ISSUE TITLE
Sagiv, Amir: TODOs

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/IntelliJ-Spartanizer#9]
_From @amirsagiv83 on October 30, 2016 12:45_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon:
- [x]  Make sure you present yourself by a readable **nick**
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#619_

**Comment by zvili** [comment]
_From @amirsagiv83 on October 30, 2016 12:47_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @inbalzukerman on October 31, 2016 13:22_

Nice Karma page :+1: 
Check out mine #684  :)

**Comment by zvili** [comment]
_From @Shahar-Y on October 31, 2016 13:32_

All other karma pages are stale and pale compering yours, oh great Sagiv!
Ihumbly request that you visit mine at #665

**Comment by zvili** [comment]
_From @EliaTraore on October 31, 2016 14:1_

yo ho check that out #694
nice page btw 👌

**Comment by zvili** [comment]
_From @RonGatenio on October 31, 2016 18:19_

What a beautiful page! Have some karma 🌟 🌠 ❇️ 🎇 ✨  🌠 ❇️🌟 🌠 ✨  
Now you have to give me some karma back #584... Those are the rules

**Comment by amirsagiv83** [comment]
**Results Of Sprint 1:**
The issues i contributed to:
#15 - I helped searching some IntelliJ plugins that might be helpful to our own plugin.
#24 - advising.
#23 - Worked and still Workind with Roey Maor trying to implement Leonidas with Psi. I've investigated the    Psi structure and found a way to create Trees from Strings.
#16 - I helped Anna and found a way to import jars to the IntelliJ so we will be able to **maybe** use the jdt dom library inside IntelliJ.
#6 - I started working on translating the auxiliary layer from eclipse to work with Psi, including learning and investigating the library's structure, until we decided it's not a solution we want to use for our project.

**Comment by yossigil** [comment]
Seems you did a large and good piece of work!
