### ISSUE TITLE
visitCallExpression in "type"

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#91]
I want to test this visit method but I can't find the difference between "PsiCallExpression" and 'PsiMethodCallExpression". There is no proper documentation, so an example to PsiCallExpression which is not PsiMethodCallExpression will be great

**Comment by RoeiRaz** [comment]
PsiMetodCallExpression and _PsiNewExpression_ interfaces are both inheriting from PsiCallExpression. So i guess the following code is a valid example:  <pre>Object a = <i><b>new Object()</b></i> ; </pre>

**Comment by michalcohen** [comment]
Thanks! 👍
