### ISSUE TITLE
visitMethodReferenceExpression in "type"

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#92]
I want to test this visit method but I can't find an example to 'PsiMethodReferenceExpression" (simple method call expression doen't create this element). There is no proper documentation, so an example to PsiMethodReferenceExpression will be great

**Comment by RoeiRaz** [comment]
```java
Function<PsiElement, Boolean> identifier = iz::identifier;
```
The rvalue here (`iz::identifier`) is a reference to a static method, and is parsed as PsiMethodReferenceExpression.

**Comment by michalcohen** [comment]
Thanks!
