### ISSUE TITLE
visitRequiresStatement in "type"

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#93]
I want to test this visit method but I can't find an example to 'PsiRequiresStatement". There is no proper documentation, so an example to PsiRequiresStatement will be great.

**Comment by RoeiRaz** [comment]
Are you looking for code example that has PsiRequiresStatement element in it? if so, i think that the following links are relevant:
https://en.wikipedia.org/wiki/Java_Module_System
http://openjdk.java.net/projects/jigsaw/spec/sotms/#module-declarations
They talk about an expansion for java (9) that allows to define modules that can depend on (require) resources from other modules:
```Java9
module com.foo.bar {
    requires com.foo.baz; // <-- PsiRequiresStatement
    exports com.foo.bar.alpha;
    exports com.foo.bar.beta;
}
```

**Comment by michalcohen** [comment]
I've tried the following code: createStatementFromText("requires " + module + ";", getTestFile()) where module is "com" or other module name, and received PsiDeclarationStatement. Are you sure it is supported? Can the type be determined by the enclosing context? (class/ interface/ module)

**Comment by RoeiRaz** [comment]
despites its name, _PsiRequiresStatement_ inherits directly from _PsiElement_ and not from _PsiStatement_, so i think you can't create it with _createStatementFromText_. instead try to use _createModuleFromText_ and then extract the relevant requires statement.
Very primitive example:
```java
private PsiRequiresStatement parseRequiresStatement(String snippet) {
        String wrappedSnippet = "module $ {" + snippet + "}";
        PsiJavaModule psiModule = JavaPsiFacade.getElementFactory(getProject()).createModuleFromText(wrappedSnippet);
        return PsiTreeUtil.getChildOfType(psiModule, PsiRequiresStatement.class);
    }
```

**Comment by michalcohen** [comment]
After the discussion today, this method is now irrelevant. Thanks! @RoeiRaz
