### ISSUE TITLE
Make it possible to use default ID in stub methods

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#97]
So generic parts that won't be used in the "to" tree can be evaluated with no user chosen ID.

**Comment by amirsagiv83** [comment]
@AnnaBel7 , can you update us on the progress in a couple of words?

**Comment by AnnaBel7** [comment]
I added the default id stubs, most of the changes were in `PsiTreeTipperBuilderImpl`
